name: build
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: build, pack & publish
    runs-on:  ubuntu-latest

    steps:
     - uses: actions/checkout@v3
     - name: Setup dotnet ${{ matrix.dotnet-version }}
       uses: actions/setup-dotnet@v3
       with:
         dotnet-version: | 
                          3.1.x
                          5.0.x
                          6.0.x
                          7.0.x

     - name: Clean nuget
       run: dotnet nuget locals all --clear
     - name: Build
       run: dotnet build -c Release
     - name: Test
       if: success()
       run: dotnet test -c Release

      # Publish
     - name: publish on version change
       id: publish_nuget
       uses: alirezanet/publish-nuget@v3.0.4
       if: ${{ success() && (github.event_name == 'push' || github.ref == 'refs/heads/main')}}
       with:
         # Filepath of the project to be packaged, relative to root of repository
         PROJECT_FILE_PATH: src/dsian.TwinCAT.AdsViewer.CapParser.Lib/dsian.TwinCAT.AdsViewer.CapParser.Lib.csproj
         NUGET_KEY: ${{secrets.NUGET_API_KEY}}
